#!/usr/bin/env bash

set -euo pipefail

: "${TARGET_BRANCH:=master}"

if [[ ! -s /tmp/commits.txt ]]; then
  echo "No packages need updating."
  exit 0
fi

while IFS=' ' read -r sha msg; do
  pkg=""
  version_diff=""

  if [[ "$msg" =~ recipes\((.*)\):.(.*) ]]; then
    pkg="${BASH_REMATCH[1]}"
    version_diff="${BASH_REMATCH[2]}"
  fi

  # prepend package namespace, if missing
  if [[ ! "$pkg" =~ ^pkgs\. ]]; then
    pkg="pkgs.$pkg"
  fi

  if ! jq -e --arg pkg "$pkg" 'any(. == $pkg)' /tmp/valid-packages.json >/dev/null; then
    echo "$pkg is not a valid forge package, skipping."
    continue
  fi

  branch="update/$pkg"

  echo "Creating PR for $pkg ($version_diff) on $branch"
  git checkout -b "$branch" origin/"$TARGET_BRANCH"

  if ! git cherry-pick "$sha"; then
    echo "Cherry-pick failed for $pkg, skipping."
    git cherry-pick --abort
    continue
  fi

  if ! git push --force origin "$branch"; then
    echo "Push failed for $pkg, skipping."
    continue
  fi

  PR_BODY="
  ## Package update

  Update \`$pkg\` to the latest version.

  *PR auto-generated by the [weekly package-update workflow](../actions/workflows/weekly-package-update.yml).*
  "

  EXISTING_PR=$(gh pr list --head "$branch" --state open --json number --jq '.[0].number')

  if [[ -n "$EXISTING_PR" ]]; then
    echo "PR already exists (#$EXISTING_PR) for $pkg. Updating title/body."
    gh pr edit "$EXISTING_PR" \
      --title "$msg" \
      --body "$PR_BODY" \
      2>&1
    continue
  fi

  gh pr create \
    --title "$msg" \
    --body "$PR_BODY" \
    --head "$branch" \
    --base "$TARGET_BRANCH" \
    --label automated \
    2>&1

done </tmp/commits.txt
