Domains:
	example.com:
		ClientSettingsDomain: mail.example.com
		LocalpartCatchallSeparator: +

		DKIM:
			Selectors:
				2026a:
					Expiration: 72h
					PrivateKeyFile: /var/lib/mox/config/dkim/dkima.rsa2048.privatekey.pkcs8.pem

				2026b:
					Expiration: 72h
					PrivateKeyFile: /var/lib/mox/config/dkim/dkimb.rsa2048.privatekey.pkcs8.pem

			Sign:
				- 2026a

		DMARC:
			Localpart: dmarcreports
			Account: admin
			Mailbox: DMARC

Accounts:
	admin:
		Domain: example.com

		Destinations:
			admin@example.com: nil

		SubjectPass:
			Period: 12h0m0s

		RejectsMailbox: Rejects

		AutomaticJunkFlags:
			Enabled: true
			JunkMailboxRegexp: ^(junk|spam)
			NeutralMailboxRegexp: ^(inbox|neutral|postmaster|dmarc|tlsrpt|rejects)

		JunkFilter:
			Threshold: 0.950000

			Params:
				Onegrams: true
				MaxPower: 0.010000
				TopWords: 10
				IgnoreWords: 0.100000
				RareWords: 2

		NoCustomPassword: true

MonitorDNSBLs:
	- sbl.spamhaus.org
	- bl.spamcop.net
