DataDir: /var/lib/mox/data
LogLevel: debug
User: mox
Hostname: mail.example.com

AdminPasswordFile: adminpasswd

Postmaster:
	Account: admin
	Mailbox: Postmaster

Listeners:
	internal:
		IPs:
			- 0.0.0.0

		Hostname: localhost

		AccountHTTP:
			Enabled: true
			Port: 8080

		AdminHTTP:
			Enabled: true
			Port: 8081

		WebmailHTTP:
			Enabled: true
			Port: 8082

		IMAP:
			Enabled: true
