name: Hydra build status

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  check-hydra-build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64-linux
          - aarch64-linux

    name: Check build status
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0

      - name: Generate packages file
        run: >
          nix eval --json --file maintainers/list-nixpkgs.nix packages --arg showBroken false
          > packages.json

      - name: Check build status
        run: >
          nix run github:imincik/nix-utils#hydra-build-status -- --failed-only --platforms ${{ matrix.platform }} --file packages.json
          > "$GITHUB_STEP_SUMMARY"
