name: Test templates

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      template:
        description: "Template to test"
        required: true
        type: choice
        options:
          - provider
          - consumer

permissions: {}

jobs:
  test-provider-hello-nix:
    name: Test provider template (hello-nix app)
    uses: ./.github/workflows/build-template.yml
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.template == 'provider'
    with:
      template: provider
      pkg: hello-nix
      app: hello-nix
      test_app: true
      test_forge_ui: true

  test-provider-hello-web:
    name: Test provider template (hello-web app)
    uses: ./.github/workflows/build-template.yml
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.template == 'provider'
    with:
      template: provider
      pkg: hello-web
      app: hello-web
      test_app: true
      test_forge_ui: true

  test-provider-multi-component:
    name: Test provider template (multi-component app)
    uses: ./.github/workflows/build-template.yml
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.template == 'provider'
    with:
      template: provider
      pkg: hello-web
      app: multi-component
      test_app: true
      test_forge_ui: true

  test-consumer:
    name: Test consumer template
    uses: ./.github/workflows/build-template.yml
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.template == 'consumer'
    with:
      template: consumer
      pkg: himalaya
      app: himalaya
      test_app: true
