name: Test templates

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      template:
        description: "Template to test"
        required: true
        type: choice
        options:
          - provider
          - consumer

permissions: {}

jobs:
  test-provider:
    name: Test provider template
    uses: ./.github/workflows/build-template.yml
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.template == 'provider'
    with:
      template: provider
      pkg: hello-nix
      app: hello-nix
      test_shell: true
      test_forge_ui: true

  test-consumer:
    name: Test consumer template
    uses: ./.github/workflows/build-template.yml
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.template == 'consumer'
    with:
      template: consumer
      pkg: hello-web
      app: example
      test_shell: true
      test_container: true
      test_vm: true
      test_forge_ui: false
