name: Weekly Flake inputs update

on:
  schedule:
    - cron: "0 1 * * 0" # Each Sunday 1am
  workflow_dispatch:

jobs:
  update:
    name: Update ${{ matrix.name }} flake input
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: nixpkgs
            flake_input: nixpkgs
            pr_branch: flake-update-nixpkgs-pr
            commit_message: "flake: weekly nix flake update"

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0

      - name: Update ${{ matrix.name }} flake input
        run: nix flake update ${{ matrix.flake_input }}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v8
        with:
          add-paths: |
            flake.lock
          title: "flake: automatic update of ${{ matrix.name }} input"
          body: |
            Update ${{ matrix.name }} input to the latest revision.
            PR auto-generated by [create-pull-request][1].

            [1]: https://github.com/peter-evans/create-pull-request
          branch: ${{ matrix.pr_branch }}
          delete-branch: true
          commit-message: ${{ matrix.commit_message }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          # Token owner: https://github.com/imincik
          # Permissions:
          #   * Read access to metadata
          #   * Read and Write access to code and pull requests
          token: ${{ secrets.FLAKE_UPDATE }}
          labels: automated
